site_name: Bluepy Documentation
nav:
  - Home: index.md
  # TODO: implement these
  # - Getting Started:
  #   - Installation: getting-started/installation.md
  #   - Usage: getting-started/usage.md
  # - Features: features.md
  # - Commands: commands.md
  # - Project layout: project-layout.md
  # - Configuration: configuration.md
